# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: domcyrus.RustNet
PackageVersion: 1.7.0
InstallerType: wix
Scope: machine
InstallationMetadata:
  Files:
  - RelativeFilePath: rustnet.exe
    FileType: launch
    InvocationParameter: --version
Installers:
- Architecture: x86
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x86
  InstallerUrl: https://github.com/domcyrus/rustnet/releases/download/v1.7.0/Rustnet_Windows_32-bit.msi
  InstallerSha256: 14132271C52F2071F553A4B6834E5EC68EBC61465BDDBD64D22D9573772D09B6
- Architecture: x64
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x64
  InstallerUrl: https://github.com/domcyrus/rustnet/releases/download/v1.7.0/Rustnet_Windows_64-bit.msi
  InstallerSha256: 070B366C28BCA5D0885BE3A298BE82785AC5FCD60C36346776C71716583EC23C
ManifestType: installer
ManifestVersion: 1.12.0
